arr = [
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                    wwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                              wwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                              wwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                              wwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                              wwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                              wwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww    wwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           wwwwwwwwwwwwwwwwwwwwwwwwwwwwww                ww        ww               www",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           wwwwwwwwwwwwwwwwwwwwwwwwwwwwww                ww        ww               www",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           ww        wwwwwwwwwwwwwwwwwwww                                           www",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           ww        ww             wwwww                                           www",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           ww        ww             wwwww                ww        ww               www",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           ww        ww             wwwww                ww        ww               www",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                    wwwwwwwwwwwwwwwwwwwwwww        wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                    wwwwwwwwwwwwwwwwwwwwwww        wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           ww                       wwwwwwwwwwwwwwwwwwwwwww        wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww        wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww   wwww             wwwwwwwwwwwwwwwwww               wwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww       ww  wwwwwwwwww                           w       wwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww       ww  wwwwwwwwww                          www         wwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww       ww  ww      ww          wwww           wwwww          wwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww       ww  ww      ww          wwww        wwwwwwwwww        wwwwwwwwwwww",
    "wwwwww                    wwwwwwwwwwwwwwwwwwww       ww  ww      ww     wwwwwwwwwwwwwwwwwwwwwwwwwwwww      wwwwwwwwwwww",
    "wwwwww                    wwwwwwwwwwwwwwwwwwww       ww  ww      ww     ww           ww         ww                   ww",
    "wwwwww                    wwwwwwwwwwwwwwwwwwww       ww  ww             ww           ww         ww         x         ww",
    "wwwwww                    wwwwwwwwwwwwwwwwwwwwww   wwwwwwww                          ww         ww                   ww",
    "wwwwww                    wwwwwwwwwwwwwwwwwwww                   ww     ww           ww         ww                   ww",
    "wwwwww                    wwwwwwwwwwwwwwwwwwww                   ww     ww           ww         ww                   ww",
    "wwwwww                    wwwwwwwwwwwwwwwwwwww                   ww     wwwwwwwwwwwwwwwww    wwwwwwww                ww",
    "wwwwwwwwwwwww      wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww     ww           wwww                            ww",
    "wwwwwwwwwwwww                                                           ww           wwwwwwww       wwwwwww    wwwwwwww",
    "wwwwwwwwwwwww                                                                        www                             ww",
    "wwwwwwwwwwwww                                                           ww           www                             ww",
    "wwwwwwwwwwwww                              wwwwwwwwwwwwwwwwwwwwwwww     ww           www            wwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
]



