arr = [
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                       wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww             x            wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwww            wwwwwwwwwwwwwwwwwwwwwwwwww                            wwwwwwwwwwwwwwwwwwwww                wwwwwwwwww",
    "wwwwwwttttttt     wwwwwwwwwwwwwwwwwwwwwwwww           ttttttt            dwwwwwwwwwwwwwwwwwww       tttt     wwwwwwwwww",
    "wwwwwwttttttt                                         ttttttt                                        ttt     wwwwwwwwww",
    "wwwwww                                                ttttttt                                                wwwwwwwwww",
    "wwwwww        wwwwwwwwwwwww      wwwwwwwwww                              dwwwwwwwwwwwwwwwwwww      wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwww     wwwwwwwwwwwww      wwwwwwwwwww                             wwwwwwwwwwwwwwwwwwww      wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwww     wwwwwwwwwwwww      wwwwwwwwwwwww                         wwwwwwww        wwwwww      wwwwwwwww       wwww",
    "w    wwww     www  tt  ww           wwwwwwwwwwwwwwwwwd          wwwwwwwwwwww           wwwwww          wwwww        www",
    "w      ww     www      ww           wwwwwwwwwwwwwwwwww          wwwwwwwww                                           tww",
    "wtttt                  ww           wwwwwwwwwwwwwwwwww          wwwwwwwww              wwwwwwwwwwww                 ttw",
    "wtttt                  ww                wwwwwwwwwwwww          wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww    wwwww        tww",
    "w      ww     www      ww                 wwwwwwwwwwww                   wwwwwwwwwwwwwwwwwwwww         wwwww        www",
    "w    wwww     www      ww                 wwwwwwwwwwww                                    wwww     wwwwwwwww       wwww",
    "wwwwwwwww     wwwwwwwwwww               wwwwwwwwwwwwww          wwwww      ttttttttt      wwww     wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwww     wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww          wwwww                     wwww     wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwww     wwwwwwwwwwwww              wwwwwwwwwwwww          wwwwwwwwwwwwwwwwwwwwwwwwwwwwww     wwwwwwwwwwwwwwwwwwww",
    "wwwwwwwww        wwwwwwwwwwtttttttt      wwwwww                                                     wwwwwwwwwwwwwwwwwww",
    "wwwwwwwww             wwwwwtttttttt      wwww                                                        wwwwwwwwwwwwwwwwww",
    "ww                    wwwww            wwww                        wwwwwwwwwwwww    wwwwwwww          wwwwwwwwwwwwwwwww",
    "wwtttttttt     wwww   wwwww   wwwwwwwwwwwww          ttttttt       wwwwwwwwwwwww    wwwwwwwww        wwwwwwwwwwwwwwwwww",
    "wwtttttttt     wwww   wwwww   wwwwwwwwwwwww          ttttttt       wwwwwwtttt         wwwwwwwww     wwwwwwwwwwwwwwwwwww",
    "wwwwtttttt     wwww                                    ttttt       wwwwww             wwww          wwwwwwwwwwwwwwwwwww",
    "wwwww          wwww                            www                 wwwwwww           wwwww          wwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww               wwwwwwww         wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
]